### ISSUE TITLE
kpAddMainTitle function's main.cex bug?

### ISSUE THREAD

**Issue by plsysu** [bernatgel/karyoploteR#1]
Hello,
when I used the function "kpAddMainTitle", I cant change the cex of main title, is there a bug ?
It seems that  code `graphics::text(x = x, y = y, labels = , main, cex = 0.8,  ...)` have a bug.

thanks.

> kpAddMainTitle
function (karyoplot, main = NULL, ...) 
{
    if (!is.null(main)) {
        karyoplot$beginKpPlot()
        on.exit(karyoplot$endKpPlot())
        bb <- getMainTitleBoundingBox(karyoplot)
        x <- (bb$x0 + bb$x1)/2
        y <- (bb$y0 + bb$y1)/2
        graphics::text(x = x, y = y, labels = , main, cex = 0.8, 
            ...)
    }
    invisible(karyoplot)
}
<environment: namespace:karyoploteR>

**Comment by bernatgel** [comment]
Yes, there's a bug there. I'll fix it next monday when I return to the lab.

**Comment by bernatgel** [comment]
It was fixed in devel and I've fixed it in release too. Should be available in biocLite in a day or two.
