### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andyjslee** [bernatgel/karyoploteR#10]
I am getting the following when I run karyoploteR

`library(karyoploteR)`
`kp <- plotKaryotype(genome = "hg19", plot.type = 3)`

Error in graphics::par(kp$graphical.par$old.par) : 
  invalid value specified for graphical parameter "pin"
Error in graphics::par(kp$graphical.par$old.par) : 
  invalid value specified for graphical parameter "pin"

**Comment by bernatgel** [comment]
Hi @andyjslee,

I cannot reproduce the error. What version of R and Bioconductor are you using?
