### ISSUE TITLE
kpPlotGenes colour by strand? 

### ISSUE THREAD

**Issue by yuxuth** [bernatgel/karyoploteR#103]
Thank you for provide this awesome tool! 

I'm wondering is it possible to color the gene annotation  based on strand in the  kpPlotGenes function ? 

Sometime when examining a large range, the arrows is too small to see, simple color gene by strand will help tell the strand information.

Thanks!

**Comment by yuxuth** [comment]
followed the example in the ENCODE Data tutorial and solved.

**Comment by bernatgel** [comment]
Great. Thanks for letting me know you solved your issue.
