### ISSUE TITLE
flip the curve into opposite direction in the kpPlotLinks function?

### ISSUE THREAD

**Issue by yuxuth** [bernatgel/karyoploteR#104]
Hi, 
I'm wondering is it possible to flip the arcs in the kpPlotLinks function? So I can plot arcs (hic Interaction result)  under the histone coverage track.
Example as following plot.
![image](https://user-images.githubusercontent.com/17417953/114098904-04500e00-9890-11eb-8f53-c917d42a18fa.png)

Thank you!

**Comment by bernatgel** [comment]
Hi @yuxuth 

Although it should be possible and easy, it seems that the current implementation does not allow it. I'll add it to the list of enhancements/bugfixes, but  I cannot promise when it will be solved.

In the meantime, as a workaround you can plot them in data.panel=2, below the ideogram,, where they are drawn always upside-down. You can, for example use plot.type=2 with modified plot params setting ideogramheight to 0, data1height=0, data1inmargin=0 and data1outmargin=0. This will plot everything upside down, so you'll have to flip r0 and r1 in the histone coverage track to flip it again.

If this is not clear, just tell me and I'll send you an example.

Hope this helps

**Comment by yuxuth** [comment]
Thank you so much! Yes, it is very helpful.
