### ISSUE TITLE
Customize labels on specific chromosome

### ISSUE THREAD

**Issue by Zhuxitong** [bernatgel/karyoploteR#107]
Dear developers:

Is there a way to add labels to only a specific chromosome like chr1 ? kpAddLabels will add the labels to all chromosomes but sometimes this looks redundant.

And also for some other plotting functions like kpAxis, can we just add the axis to the bottom chromosome ?

Although this could be done manually in AI, I still hope there will be some direct ways to modify this during plottting.

**Comment by bernatgel** [comment]
Hi @Zhuxitong 

Hmm... no, none of the "add" functions not kpAxis has the option to specify n which chromosomes you want to draw them. It might be a nice little enhancement, but it will mean adding an additional "chromosomes" parameter to a bunch of functions, which I'll have to think about it.

For the moment you can maybe hack it playing with the col argument and passing a transparent color for the labels you don't want, but it's a quite hacky way to do that. 

If I manage to implement it anytime soon, I'll get back to you.

Bernat

**Comment by Zhuxitong** [comment]
Thanks @bernatgel , I am looking forward to that enhancement 👍
