### ISSUE TITLE
about draw the plot

### ISSUE THREAD

**Issue by zhoudreames** [bernatgel/karyoploteR#108]
I want to draw this plot by using karyoploteR,but my custome genome show all choromosome is line,it look like a little suitable.
could I achieve it by using your software? thanks 
![image](https://user-images.githubusercontent.com/54714639/125958541-afe2b441-f48b-4279-bbe6-e648dce8b0b1.png)

**Comment by bernatgel** [comment]
Hi @zhoudreames 

Sorry for the delay in responding. No, I'm sorry but it's not possible to create such a plot with karyoploteR

Bernat
