### ISSUE TITLE
re: box plots

### ISSUE THREAD

**Issue by mike-molnar** [bernatgel/karyoploteR#109]
Hi Bernat,

I have been using karyoploteR a lot lately and I think it is amazing!  Thanks for sharing it with us.  Although, I have finally come across something I am not able to do, or at least find an example of how to do it.  I have datasets of genome wide coverage levels averaged in 10,000 bp intervals, which I use for my kpPlotLoess plots across each chromosome.  I want to use those datasets to make box plots of the different coverage levels across each chromosome.  Is that possible now but I have not found it?

Thanks again,
Mike

**Comment by bernatgel** [comment]
Hi Mike,

Glad you like karyoploteR :) 

You are right you have reached the limits of karyoploteR. There's no function to create boxplots. It would be possible to build them from scratch (at the end they are only rectangles and segments) or maybe come up with a visualization showing all the data in a boxplot but using different visual elements (i.e. a different colored segments for the median, and the 1st and 3rd quartile, smaller segments at the end of the whiskers...).

If you think this would be useful fo your research and you really struggle to get it done, I think I should be to help you with it. Reopen this issue and we can talk about it.

Bernat
