### ISSUE TITLE
karyoploteR installation issue, macos 12

### ISSUE THREAD

**Issue by AMJseattle** [bernatgel/karyoploteR#118]
karyoploteR installation issue, macos 12. M1 chip - 

R 4.1.2 and RStudio 2021.09.2 Build 382
-----

I had to do various installations to solve early issues (installing
devtools, gfortran, brew...) and now I'm stuck with this:

[snip]
* installing *source* package ‘Rhtslib’ ...
** using non-staged installation via StagedInstall field
** libs
cd "htslib-1.7" && make -f
"/Library/Frameworks/R.framework/Resources/etc/Makeconf" -f
"Makefile.Rhtslib"
Makefile.Rhtslib:128: warning: overriding commands for target `.c.o'
/Library/Frameworks/R.framework/Resources/etc/Makeconf:169: warning:
ignoring old commands for target `.c.o'
[snip]
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I.
-I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o cram/cram_io.o
cram/cram_io.c

*cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found*#include

^~~~~~~~
1 error generated.
make[1]: *** [cram/cram_io.o] Error 1
make: *** [htslib] Error 2
ERROR: compilation failed for package ‘Rhtslib’
* removing
‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rhtslib’
ERROR: dependency ‘Rhtslib’ is not available for package ‘Rsamtools’
[snip]
ERROR: dependencies ‘regioneR’, ‘Rsamtools’, ‘rtracklayer’, ‘biovizBase’,
‘GenomicFeatures’, ‘bamsignals’, ‘VariantAnnotation’ are not available for
package ‘karyoploteR’
* removing
‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/karyoploteR’

---
Any help would be appreciated.

**Comment by bernatgel** [comment]
Hi @AMJseattle 

I'm afraid I won't be able to help here. I don't have access to any mac and even less to an M1 mac.

What I can assure you is that karyoploteR is pure R and does not have any C code nor includes DIRECT dependencies on any external libraries. The problem you are seeing seems to be related to HTSlib and the package Rhstlib. I would start trying to install Rhtslib directly and seeking help to install that if it fails. This is a widely used package so I'm sure you'll be able to find someone who's succeeded installing it.

I'm sorry I'm not more useful with this issue.

Bernat
