### ISSUE TITLE
kpPlotBigWig: added ability to start with a pre-loaded bigwig

### ISSUE THREAD

**Issue by tovahmarkowitz** [bernatgel/karyoploteR#123]
Hi,

I work with a lot of ChIP-seq data and often need to plot patterns across a chromosome for publication purposes. Unfortunately, the bigwig files I am working with often have additional chromosomes (like chrM) or missing chromosome information (ie, no sex chromosomes) so the seqlevels don't automatically match between those loaded into the kp object and the bigwig. The ability to preload a bigwig file using rtracklayer myself and adjust the seqlevels using GenomicRanges before interacting with the karyoploteR object would be very helpful.

Thank you.

**Comment by bernatgel** [comment]
Hi @tovahmarkowitz 
You closed the issue. I understand you solved your problems yourself. Is that right?
Bernat

**Comment by tovahmarkowitz** [comment]
Hi Bernat,

I realized the issue I posted was related to a warning message and that my actual problem was something else that I eventually solved.

Tovah

From: Bernat Gel ***@***.***>
Date: Thursday, May 19, 2022 at 8:25 AM
To: bernatgel/karyoploteR ***@***.***>
Cc: Markowitz, Tovah (NIH/NIAID) [C] ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [bernatgel/karyoploteR] kpPlotBigWig: added ability to start with a pre-loaded bigwig (Issue #123)

Hi @tovahmarkowitz<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftovahmarkowitz&data=05%7C01%7Ctovah.markowitz%40nih.gov%7Cde35c7165f794953713708da3992b538%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637885599512614071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EsucgyKOFsB6AkfZiz55guxnAnB6wJTKIQrCn4A57bc%3D&reserved=0>
You closed the issue. I understand you solved your problems yourself. Is that right?
Bernat

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbernatgel%2FkaryoploteR%2Fissues%2F123%23issuecomment-1131621193&data=05%7C01%7Ctovah.markowitz%40nih.gov%7Cde35c7165f794953713708da3992b538%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637885599512772576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YzjpC1aHxkeePoQ4UHM%2Bl%2BADWdKhXuNPRy9FskuQJcw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFJBK2CG5TO5D2GN7QK76FDVKYXLJANCNFSM5WJNU4PA&data=05%7C01%7Ctovah.markowitz%40nih.gov%7Cde35c7165f794953713708da3992b538%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637885599512772576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uNgQk04LQWxc0GLIaAUxCKGWa6RNMvSQTwQVCSG7zdA%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
