### ISSUE TITLE
auto adjust the Y-axis height

### ISSUE THREAD

**Issue by nirvana693** [bernatgel/karyoploteR#126]
Hi, 

Thank you for such a awesome package! 

I am trying to plot coverage using bedgraph file and everything works fine. I am finding difficulty to set data driven Y-axis height chromosome wise. For ex: ymax of chr1 is 10 but chr2 could be 25. 

How do I set data driven Ymax values chromosome wise?

**Comment by bernatgel** [comment]
Hi @nirvana693 

It depends on the specific function you are using, but you might need to compute these values by yourself and then use them to guide your plotting (ymax=XXXX)

Hope this helps!
