### ISSUE TITLE
kpPlotManhattan not plotting manhattan plot

### ISSUE THREAD

**Issue by Maetchild** [bernatgel/karyoploteR#127]
Hello,

I'm having troubles with kpPlotManhattan. It does plot the genomewideline and the suggestive one, but not the SNPs data.

My input GRobject is the following:
![Schermata 2022-07-07 alle 12 19 02](https://user-images.githubusercontent.com/108892382/177832742-133d75f5-e8fb-466f-9f9c-1ecb0e95eb94.png)

And I'm using this code:
`kp <- plotKaryotype(plot.type=2, genome=bos.genome, chromosomes = c("chr4", "chr16"))`
`kpAxis(kp, ymax=20)`
`kp <- kpPlotManhattan(kp, data=gr, pval=gr$p, ymax=20, points.col="2blues")`

What I obtained is this, apparently it does not read my p-values:
![Schermata 2022-07-07 alle 12 17 01](https://user-images.githubusercontent.com/108892382/177832308-9330be29-9ee1-4ef3-9f10-e476c5c2d9f3.png)

I'm sure it's something stupid by my side, just I cannot understand what. Do you have any insight?
(I'm using: 
_R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.4
other attached packages:
BSgenome.Btaurus.UCSC.bosTau9_1.4.2 BSgenome_1.64.0                    
rtracklayer_1.56.1                  Biostrings_2.64.0                  
XVector_0.36.0                      dplyr_1.0.9                        
readxl_1.4.0                        BiocManager_1.30.18                
data.table_1.14.2                   karyoploteR_1.22.0                 
regioneR_1.28.0                     GenomicRanges_1.48.0               
GenomeInfoDb_1.32.2                 IRanges_2.30.0                     
S4Vectors_0.34.0                    BiocGenerics_0.42.0_

Thank you so much!

**Comment by Maetchild** [comment]
Solved!! The chromosomes have to be expressed as "chr1", "chr2", ecc... and not as "1", "2",...

Great package by the way!!

**Comment by bernatgel** [comment]
Yes! This is a very common problem with karyoploteR! I'm debating between creating a page explaining the problem in the tutorial site, o trying to identify this problem on the fly and warn the user about it. But I'm sure it's been a problem difficult enough for many people to ditch it before using it. In any case, glad you found the problem!
