### ISSUE TITLE
Conda/Mamba installation: nothing provides r 3.2.2* needed by r-digest-0.6.9-r3.2.2_0

### ISSUE THREAD

**Issue by JEstabrook** [bernatgel/karyoploteR#128]
R3.2.2 is no longer available via the r channel in conda causing installation of the package to fail due to no channels providing the appropriate package versions specified by the conda build. Could you provide an updated conda build that resolves these dependencies from r-digest? 

```
mamba create -c bioconda -c r -n karyoploter bioconductor-karyoploter
...
Encountered problems while solving:
  - nothing provides r 3.2.2* needed by r-digest-0.6.9-r3.2.2_0
```

**Comment by bernatgel** [comment]
Hi @JEstabrook 

I'm sorry, but I have no control over conda installation or recipes. This is all managed by the Bioconductor and Bioconda teams, I think.

In any case, R 3.2.2 is a VERY old version, so I think the best would be to work with a newer R and Bioconductor version (karyoploteR will be newer with more features, too)

Hope this helps
