### ISSUE TITLE
some blocks are lacking in kpRect function

### ISSUE THREAD

**Issue by zhoudreames** [bernatgel/karyoploteR#132]
This figure showed all color blocks when I saved the .png;
<img width="737" alt="image" src="https://user-images.githubusercontent.com/54714639/212793757-abc057e3-9807-4157-b99b-b43f9034a785.png">
but some blocks is disappeared when i saved .pdf:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/54714639/212793861-4c3daadf-408e-4737-bad4-1723cb4f5599.png">
This my code:
```
custom.genome <- toGRanges("Desktop/01.Goldenpigs/SDs/DRC19_SD/DRC.genome.txt")
custom.cytobands <- toGRanges("Desktop/GP_Result/Figure1/DRCv20_cytokype.txt")
region<- read.csv("Desktop/GP_Result/Figure1/DRC.color.bed",sep="\t",header = F)
kp <- plotKaryotype(genome = custom.genome,plot.type = 1)
 kpRect(kp, chr=region$V1, x0=region$V2, x1=region$V3, y0=-0.34, y1=-0.11, col=region$V5,border=NA,data.panel = 1)
```
I want to save complete figure with pdf format, can i do it? Thanks~

**Comment by zhoudreames** [comment]
@kant @mtmorgan @bernatgel @vobencha  I am so sorry to disturb you, can you help me? Thanks~

**Comment by bernatgel** [comment]
Hi @zhoudreames 

To give a complete answer, I'd need some more information. How are you saving your plots? Can you give me a chunk of code and a data file producing this error? Right now with no data to actually test it and without the code to save the plots I can only speculate on the problem.

So, a first possibility is that the red regions are not a single big region but a lot of very small ones together. If this is the case, different graphical devices (png and pdf) might represent them differently. One thing you could try is to give the regions a single pixel border changing `border=NA` to `border=region$V5`. That would make sure that even the tiniest region is given at least a pixel in your plot. 

One more thing: you are using negative y values to plot on the chromosomes themselves. This is a difficult way to do it (although you did a pretty good job, to be honest). If you want to plot on the chromosomes you could change `data.panel=1` to `data.panel="ideogram"` and the use `y0=0` and `y1=1` to plot on the ideogram itself. You have some more information about this in the tutorial page: at https://bernatgel.github.io/karyoploter_tutorial//Tutorial/DataPanels/DataPanels.html

Hope this helps

Bernat
