### ISSUE TITLE
Blue bands on ideogram

### ISSUE THREAD

**Issue by mkyriak** [bernatgel/karyoploteR#134]
Hello, thank you for the very detailed documentation of your tool.

I have a question regarding the plotted chromosomes.

When the ideogram is plotted (like in this [example](https://bernatgel.github.io/karyoploter_tutorial//Examples/PlotGenes/PlotGenes.html), there are some blue bands on chr13, chr14, chr15, chr21 and chr22.
Could you please explain what are these regions colored in blue?

Thank you in advance for your time and kind help!
Maria

**Comment by bernatgel** [comment]
Hi Maria,

Thanks for the kind words :)

The colors used to draw the cytobands are adapted from the ones used in circos and can be found in https://github.com/bernatgel/karyoploteR/blob/master/R/color.R

The blueish parts correspond to bands annotated as "stalk", which usually corresponds to the short arms of acrocentric chromosomes. The actual cytobands annotation used is defined by UCSC and you should be able to find additional information on the actual definition of each cytoband in their documentation.

Regarding the colors, it is possible to use different color schemas for the cytobands and even to use your own should you prefer it. It is not very well documented yet (karyoploteR customizations are huuuuge and difficult to document!) but I can give you more information if you need it.

Bernat
