### ISSUE TITLE
How to use karyoploteR for non-model species?

### ISSUE THREAD

**Issue by Song-10-YF** [bernatgel/karyoploteR#135]
Hello.
I am using a non-model species, how do I iuput and install a new genome for analysis in karyoploteR. 
For example I want to build a transposon library for a certain species like the example: TxDb.Hsapiens.UCSC.hg19.knownGene.

Thanks and I look forward to your reply.
Yanfeng

**Comment by bernatgel** [comment]
Hi Yanfeng,

Please bear in mind that karyoploteR is a plotting library and only plotting. It will not perform any analysis of any kind.

You can produce plots for non-model organisms as shown in https://bernatgel.github.io/karyoploter_tutorial//Tutorial/CustomGenomes/CustomGenomes.html but you'll have to provide it the data you want to plot, as it will not produce any data by itself.

Hope this helps

Bernat
