### ISSUE TITLE
Borders of chromosomes in plot type 6 are not all the same

### ISSUE THREAD

**Issue by jcsokol** [bernatgel/karyoploteR#142]
Hi! 

Thank you so much for this package. I just noticed that when using plot type 6, the borders of the chromosomes are not all the same color. I noticed this in my own plots, and also noticed it in the plot displayed in your tutorial for plot type 6 (see the attached image). This might be some sort of aliasing effect. Is there a way to make sure that the borders all have the exact same color, and is there even a way to control the thicknesses of these borders? 

![Figure6-1](https://github.com/bernatgel/karyoploteR/assets/37128421/008e1a88-5ea8-495a-8580-dc5662a28aa7)

Thanks in advance. 

Jan

**Comment by bernatgel** [comment]
Hi @jsokol94 

You are right about this. I also think it's an antialiasing problem, but a bit more complex than it seems. 

The borders you see here are not actually borders of the gray rectangles, but the parts of the chromosome ideograms that  the gray rectangle failed to cover.

I think the cleanest look for this would be to NOT plot the ideograms so no "border" is shown. 

```
kp <- plotKaryotype(plot.type=6, main="plot.type=6", ideogram.plotter = NULL)
kpDataBackground(kp, lwd=23)
kpText(kp, chr="chr1", x=60e6, y=0.5, labels="data.panel=\"ideogram\"", data.panel = "ideogram")
```
![image](https://github.com/bernatgel/karyoploteR/assets/919489/d993a599-1750-4a33-b5f9-2994c83ca814)

And if you'd like a border around the data panel, the best option is to plot a rectangle using `kpRect` and giving it the size of the chromosomes (you can get those from the `kp` object). With this, you can control the width, color and style of the borders.

```
kp <- plotKaryotype(plot.type=6, main="plot.type=6", ideogram.plotter = NULL)
kpDataBackground(kp, lwd=23)
kpText(kp, chr="chr1", x=60e6, y=0.5, labels="data.panel=\"ideogram\"", data.panel = "ideogram")

kpRect(kp, data=kp$genome, y0=0, y1=1, col=NA, border="red", lwd=2, lty=3)
```

![image](https://github.com/bernatgel/karyoploteR/assets/919489/8514045e-162f-46eb-b502-f6cc7e86281d)


Hope this helps!
