### ISSUE TITLE
installation fail

### ISSUE THREAD

**Issue by DittmanC** [bernatgel/karyoploteR#143]
wonder how can I install the previous version of R so that I can use this package? Thanks

BiocManager::install("karyoploteR")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package =
"BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.15 (BiocManager 1.30.21), R 4.2.1 (2022-06-23)
Error in paste(.sQuote(doing), collapse = ", ") : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BiocManager/R/BiocManager.rdb' is corrupt
In addition: Warning messages:
1: In paste(.sQuote(doing), collapse = ", ") :
  restarting interrupted promise evaluation
2: In paste(.sQuote(doing), collapse = ", ") :
  internal error -3 in R_decompress1

I have also tried,
install.packages("karyoploteR")
Warning in install.packages :
  package ‘karyoploteR’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by bernatgel** [comment]
Hi @DittmanC 

I don't know what happened to your R install, but using `BiocManager::install("karyoploteR")` should install karyoploteR right away. I've never seen an error like this in our tests nor on the daily Bioconductor tests. 

Hope you can fix it
