### ISSUE TITLE
Error: package load failed

### ISSUE THREAD

**Issue by HannibalMD** [bernatgel/karyoploteR#15]
Hello,
I am having difficulty installing KaryoploteR. 
I updated R to 3.5.1 and followed to the installation instructions. However, when I opened KaryoploteR, I received several errors (see below). Then, when I tried to plot an ideogram, the commands were not recognized. Any help/ideas? 

> source("https://bioconductor.org/biocLite.R")
Bioconductor version 3.7 (BiocInstaller 1.30.0), ?biocLite for help
> biocLite("karyoploteR")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.7 (BiocInstaller 1.30.0), R 3.5.1 (2018-07-02).
Installing package(s) ‘karyoploteR’
trying URL 'https://bioconductor.org/packages/3.7/bioc/bin/macosx/el-capitan/contrib/3.5/karyoploteR_1.6.0.tgz'
Content type 'application/x-gzip' length 2800531 bytes (2.7 MB)
==================================================
downloaded 2.7 MB

> library(karyoploteR)
Loading required package: regioneR
Loading required package: memoise
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colMeans,
    colnames, colSums, dirname, do.call, duplicated, eval, evalq,
    Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply,
    lengths, Map, mapply, match, mget, order, paste, pmax, pmax.int,
    pmin, pmin.int, Position, rank, rbind, Reduce, rowMeans, rownames,
    rowSums, sapply, setdiff, sort, table, tapply, union, unique,
    unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:plyr’:

    rename

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges

Attaching package: ‘IRanges’

The following object is masked from ‘package:plyr’:

    desc

Loading required package: GenomeInfoDb
Loading required package: BSgenome
Loading required package: Biostrings
Loading required package: XVector

Attaching package: ‘XVector’

The following object is masked from ‘package:plyr’:

    compact

Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit

Loading required package: rtracklayer
Error: package or namespace load failed for ‘rtracklayer’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘XML’
Error: package ‘rtracklayer’ could not be loaded

> kp <- plotKaryotype(genome="hg19")
Error in plotKaryotype(genome = "hg19") : 
  could not find function "plotKaryotype"

**Comment by bernatgel** [comment]
Hi @HannibalMD 
It seems the problem is with the installation of rtracklayer, and in particular, that it does'nt find the XML package. Can you try to manually install XML first with 

  install.packages("XML")

and then try again?
