### ISSUE TITLE
kpAxis in zoomed plots

### ISSUE THREAD

**Issue by bernatgel** [bernatgel/karyoploteR#18]
kpAxis plot the axis at the first or last position of the chromosomes. Therefore, when using zoom, axis are not visible. Change the code to plot them at the begining/end of the plot.region. This should accomodate all situations.

**Comment by molbio-dresden** [comment]
Hello @bernatgel, 

thank you for providing such a helpful package. 

I also ran into the described kpAxis-Zoom issue. So what can I do to have a visible Axis? In which way should I change the code to plot the axes at the begining/end of the plot.region? I would appreciate the help.

**Comment by molbio-dresden** [comment]
Hello @bernatgel, I solved it by zooming in the negative space 5' of the starting chromosome, i.e.

`zoom.region <- toGRanges(data.frame("chr01", -20000000, 138000000))`

In the region between -20000000 and 0 bp, the Y axis appeared again.

**Comment by bernatgel** [comment]
Ook, kind of a hack but it actually makes sense. I'll try to find some time to fix the bug so kpAxis works in any zoom and get back to you.

**Comment by molbio-dresden** [comment]
Thank you, that would be highly appreciated!

**Comment by bernatgel** [comment]
Ok, this has been fixed in version 1.6.2 in the RELEASE_3_7 branch (the current release in bioconductor) and in version 1.7.3 in master branch (devel version in bioconductor). 

To get it you can either wait a a day or two for Bioconductor to build the new version and update with biocLite as usual or install the newest version from github with devtools.
