### ISSUE TITLE
Issue with kpAddCytobandsAsLine

### ISSUE THREAD

**Issue by svarsen** [bernatgel/karyoploteR#19]
Hey, 
I am trying to generate a plot.type = 4 karyoplot with a custom genome using the description here: https://bernatgel.github.io/karyoploter_tutorial//Examples/GeneDensity/GeneDensity.html
Everything is working ok but the kpAddCytobandsAsLine code does not add the chromosome bars. Relevant code is listed below:
`kp <- plotKaryotype(genome = Chr_sizes_GR, cytobands = gene_bed_GR, plot.type=4, ideogram.plotter = NULL, labels.plotter = NULL)
kpAddCytobandsAsLine(kp)
kpAddChromosomeNames(kp, srt=45)

ordered <- DEG_GR[order(DEG_GR$FDR, na.last = TRUE),]
fc.ymax=ceiling(max(abs(DEG_GR$logFC.GenotypeBb)))
fc.ymin=0

kpAxis(kp, ymax=fc.ymax, ymin=fc.ymin,side = 1,cex=0.5,r0 = 0.1, r1 = 0.45)
kpPlotDensity(kp, DEG_GR,r0 = 0.1,r1=0.45)
kpAddMainTitle(kp,main=title)
kpPlotRegions(kp,data = supergene_GR,col="red", r0=0,r1=0.05)
`
with Chr_sizes_GR looking like:
GRanges object with 16 ranges and 1 metadata column:
       seqnames        ranges strand |       chr
          <Rle>     <IRanges>  <Rle> | <integer>
   [1]      lg1 [1, 26801316]      * |         1
   [2]      lg2 [1, 19642518]      * |         2
   [3]      lg3 [1, 19384547]      * |         3
   [4]      lg4 [1, 19999581]      * |         4
   [5]      lg5 [1, 15556348]      * |         5

and DEG_GR looking like:
GRanges object with 82 ranges and 8 metadata columns:
        seqnames               ranges strand |   Row.names logFC.Genotypebb logFC.GenotypeBb      logCPM         F       PValue          FDR
           <Rle>            <IRanges>  <Rle> | <character>        <numeric>        <numeric>   <numeric> <numeric>    <numeric>    <numeric>
    275     lg13   [5389892, 5393558]      * |   gene10246        5.6892339        2.2617307 -0.44775874  13.99144 1.941337e-05 2.501616e-03
    299     lg11   [1979965, 1981447]      * |   gene10268       -4.6336728       -4.6452638  0.02878333  12.80478 3.893802e-05 4.230502e-03
    435     lg16   [8349870, 8355819]      * |   gene10391        7.3021439        6.6712809  4.73588785  23.68230 2.737338e-08 7.583794e-06
    436     lg16   [8336934, 8342229]      * |   gene10392        0.7791989        0.4486888  6.25325327  11.00287 8.610967e-05 7.952228e-03

Any recommendations on how to help?
Thanks,
Sam

**Comment by bernatgel** [comment]
Hi Sam, 

Thanks for the detailed report. I've taken a look and updated the relevant code.

Both kpAddCytobands and kpAddCytobandsAsLine expect the cytobands GRanges passed to plotKaryotype to have a column named "gieStain" with values like the ones given by [UCSC](http://genome.ucsc.edu/cgi-bin/hgTables?hgsid=689261591_Aswznq1yBFU8GasORn5WaCtD2CUF&hgta_database=hg19&hgta_histoTable=cytoBand&hgta_doValueHistogram=gieStain) in their [cytoband table](http://genome.ucsc.edu/cgi-bin/hgTables?db=hg19&hgta_group=map&hgta_track=cytoBand&hgta_table=cytoBand&hgta_doSchema=describe+table+schema). 

However this was not well documented (actually, documented in any way) and not checked in code. I've updated the code to check the 'gieStain' column is present and the documentation to reflect this.

This has been corrected bot in devel and RELEASE_3_7 (the current one) and should be available in biocLite in a day or two. If you want to give it a try you can use the github version of the function.

In future versions I'll try to add some more flexibility to the cytoband specification and coloring.

Two additional concerns with you code:

  * You are using a GRAnges named `gene_bed_GR` for your cytobands. I don't know its content, but its name does not sound like the most typical data to use. Remember if you set `cytobands=NULL` it will just use a gray line as cytobands, which is usually useful for custom genomes.

  * You are setting the axis limits based on some fc computation, but the using kpPlotDensity to plot the data on them. This will create a discrepancy between the axis and the data plotted. You should either plot the axis using the limits extracted from the kp object after running kpPlotDensity (see the last code panel at https://bernatgel.github.io/karyoploter_tutorial//Tutorial/PlotDensity/PlotDensity.html) or use the same `ymax` value used in kpAxis on kpPlotDensity.

Hope this helps!
