### ISSUE TITLE
kpPlotCoverage residue

### ISSUE THREAD

**Issue by Baboon61** [bernatgel/karyoploteR#21]
Sorry to add something else to your "to do" list. I found something unpleasant in kpPlotCoverage visualization

There is a residue from the beginning of the chromosome to the last event in the data of kpPlotCoverage. It could represent the 0 coverage value but this residue vanish after the last event...

Example talks better :

`custom.genome <- GRanges(seqnames="chr12",ranges=IRanges(1,300000),strand=NULL)`
`custom.coverage <- GRanges(seqnames=c("chr12","chr12","chr12"), ranges=c(IRanges(150000,200000),IRanges(150000,200000),IRanges(250000,260000)), strand=c("+","+","+"))`
`kp <- plotKaryotype(genome = custom.genome)`
`kpPlotCoverage(kp, data=custom.coverage)`

Either the residue is added on the full length of the chromosome, like saying it is a 0 coverage nor simply remove the residue. As you wish !

Thanks again for the great tool !

**Comment by bernatgel** [comment]
Hi  @Baboon61 

Thanks for the report and the example. You are right, the thin line  represents 0 coverage, but it's not correct as it is now, not covering the whole chromosome.

I'll take a look and see what's the best option for it. I think I'd prefer getting rid of it altogether but maybe leaving the option to the user to turn it on if desired. 

Bernat

**Comment by bernatgel** [comment]
Hi @Baboon61 

I've fixed the problem and added a new parameter to kpPlotCoverage ("show.0.cov") to control whether the line is plotted for 0 coverage regions or not (defaults to TRUE).

Just pushed to Bioconductor (devel) and github, so you can install fixed version from github now or wait a couple of days for it to be available with biocLite() (or BiocManager)

If you need me to fix this in the current version of karyoploteR I should be able to do it too.

Thanks again for the report

Bernat

**Comment by Baboon61** [comment]
Thanks for the fast fix @bernatgel 
I have waited a couple of days to get the biocLite release but I'm not able to get your patch
Is it possible to get the fix under Bioconductor version 3.6 (BiocInstaller 1.28.0) ? Which is not the last release of BiocLite. But to get the last BiocLite release I need to update my R environnement (3.5.1) and I prefer not to go this way.
Thanks

**Comment by bernatgel** [comment]
Hi @Baboon61 
I cannot modify the older versions of the package. As per Bioconductor rules I can only modify the devel branch and fix bugs in devel and release branches. With older versions the code is freezed.

You have two options: 

1. (not recommended) Force install the latest version into your system (you can use devtool::install_github("bernatgel/karyoploteR") and hope for it to work

2. (recommended) Modify the code for your kpPlotCoverage function only. I've taken the code from version 1.4.2 and applied the changes from  [this commit](https://github.com/bernatgel/karyoploteR/commit/5ab526bdccd79a4de1bd322c1df09c4ab003a800#diff-1ad7ceea3211f8b9f46f0409449684ad). The file is attached. Simply source this function **AFTER** you have loaded karyoploteR and it should work as expected. I've added a new param `show.0.cov=TRUE` to decide whether coverage 0 should be drawn or not. 

Hope this helps. If you have any other question feel free to ask

Bernat
[kpPlotCoverage.R.txt](https://github.com/bernatgel/karyoploteR/files/2615078/kpPlotCoverage.R.txt)

**Comment by Baboon61** [comment]
I chose the third option ! Update my R to 3.5 and it is working. Thank you

**Comment by bernatgel** [comment]
Hehe,

Ok! Sorry for the delay! glad it worked, though

Bernat
