### ISSUE TITLE
Plot cytobands along a custom genome

### ISSUE THREAD

**Issue by sachaallen** [bernatgel/karyoploteR#22]
Hi,

I'm trying to plot different segments along a custom genome. I can plot the chromosomes without the segments but when I add these the background image of the chromosome disappears and only the segments are visible (see below). Can you help?

![image](https://user-images.githubusercontent.com/44461953/47486133-8f132e80-d837-11e8-9516-7da0f63c9456.png)

Here is a sample of my mycytobands.txt file:

chr | start | end | name | gieStain
-- | -- | -- | -- | --
4A | 1 | 10000000 | test |  
1A | 48588720 | 57764717 | Ae_tauschii_242 |  
1A | 5.51E+08 | 555641708 | Ae_Biuncialis_550957 |  
1A | 5.72E+08 | 576343725 | Ae_Sharonensis_2170007 |  
1B | 1.2E+08 | 120881576 | Ae_speltoides_2140004 |  
1B | 1.2E+08 | 120881576 | Ae_speltoides_2140006 |  
1B | 1.2E+08 | 120881576 | Ae_Speltoides_2140008_P09 |  
1B | 1.2E+08 | 120881576 | Ae_speltoides_2140019 |  
1B | 1.2E+08 | 120881576 | Ae_speltoides_2140027 |  
1B | 1.2E+08 | 120881576 | Ae_speltoides_369666 |  

Thank you in advance!

Sacha

**Comment by bernatgel** [comment]
Hi @sachaallen ,

It really depends on what you are trying to do. 

  * If you want to plot a set of segments representing some elements detected on the genome such as 
genes or any other annotation I would suggest using [`kpPlotRegions` ](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/PlotRegions/PlotRegions.html). This will not plot ON the ideograms but above the ideograms (could be below if needed).
```
cust.genome <- toGRanges(data.frame(c("1A", "1B", "4A"), c(1, 1,1), c(8e8, 8e8, 4e8)))
myregions <- toGRanges("mycytobands.txt")   
kp <- plotKaryotype(genome=cust.genome)
kpPlotRegions(kp, data=myregions)
``` 
This will by default avoid the overlap of regions stacking them but this can be disabled if needed.

  * If you want to plot that ON the ideogram you can use the devel version or wait until the 30th of October when the new version of Bioconductor will be released and use the new option `data.panel="ideogram"` that will be available to all plotting functions. This code should work with the next release (does not work in the current one!)
```
cust.genome <- toGRanges(data.frame(c("1A", "1B", "4A"), c(1, 1,1), c(8e8, 8e8, 4e8)))
myregions <- toGRanges("mycytobands.txt")   
kp <- plotKaryotype(genome=cust.genome)
kpRect(kp, data=myregions, y0=0, y1=1, data.panel="ideogram")
```

  * If the information you are passing are REALLY cytobands, they should cover the whole chromosomes (which is not the case) and should have a [valid `gieStain` value](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/CustomGenomes/CustomGenomes.html)

**Comment by sachaallen** [comment]
Thank you very much for your help with this bernatgel.
