### ISSUE TITLE
kpPlotCoverage with scale bar

### ISSUE THREAD

**Issue by Baboon61** [bernatgel/karyoploteR#28]
Hello @bernatgel 
As it seems simple to add a scale bar by myself on a kpPlotCoverage visualization for a single chromosome, creating a scale bar from 0 to "ymax" with some intermediate ticks (or -"ymax",0,"ymax" for sense and anti-sense values). It is more tricky when the display involved multiples chromosomes...

The only solution I got for now is to try to create multiple scale bar patterns, for 1 chromosome, 2 chromosomes, 3 chromosomes... Not very clean.

Thank you, again !

**Comment by bernatgel** [comment]
Hi @Baboon61 
Have you tried to use the `kpAxis` function from the package? It manages the creation of the vertical scale bars quite nicely. 

https://bernatgel.github.io/karyoploter_tutorial//Tutorial/Axis/Axis.html

Bernat

**Comment by Baboon61** [comment]
Damn, of course it is working, i didn't dig enought... Sorry for this question and thanks for the quick reply

**Comment by bernatgel** [comment]
Sure, no problem. There are lots of functions (and some still missing in the tutorial page!) so it's normal to miss some of them!
