### ISSUE TITLE
Error in Pvivax genes tutorial

### ISSUE THREAD

**Issue by vin6** [bernatgel/karyoploteR#32]
Hello,
I'm walking through the P. vivax genes tutorial in order to troubleshoot my own custom genome plotting issues. When I get to the following code block:

pp <- getDefaultPlotParams(plot.type=2)
pp$data1outmargin <- 100
pp$data2outmargin <- 100
pp$topmargin <- 450
kp <- plotKaryotype(genome=PvP01.genome, ideogram.plotter = NULL, plot.type=2, plot.params = pp)
kpAddCytobandsAsLine(kp)

I get this error:

Error in ccf(x = start(cyto), chr = as.character(seqnames(cyto))) : 
  In coordChangeFunction: data.panel is required

I tried adding a data.panel param, but got the same error:
> kpAddCytobandsAsLine(kp, data.panel = 1)
Error in ccf(x = start(cyto), chr = as.character(seqnames(cyto))) : 
  In coordChangeFunction: data.panel is required

Why is this error showing up, and how do I fix it?

**Comment by bernatgel** [comment]
Hi @vin6,

This is an error in the package. I'll fix it and get back to you as soon as it's fixed.

Thanks for reporting this.

**Comment by bernatgel** [comment]
Hi @vin6 

This has been fixed in version 1.8.6 That's available now in github and should be available in a day or two using BiocManager

Thanks again for reporting the problem
