### ISSUE TITLE
Could I use genome assembled by myself as input to karyoploteR? 

### ISSUE THREAD

**Issue by bioinformaticspcj** [bernatgel/karyoploteR#35]
Hello,

I am a post graduate student, now I want to use  "karyoploteR" to plot my genome. But I do know that if I could use the genome assembled by myself? And if the answer is "yes", how should I do?

I am looking forward to your valuable reply.
Thanks a lot.

**Comment by bernatgel** [comment]
Sure, it's a YES. Everything in karyoploteR should work in any genome, including your own!
To use your genomes you need to create a GRange object with the names and lengths of your chromosomes

    library(karyoploteR)
    custom.genome <- toGRanges(c("1:1-10000", "2:1-9000", "3:1-7000"))
    kp <- plotKaryotype(genome=custom.genome)

You'll find more information on how to do that in the [custom genome tutorial page](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/CustomGenomes/CustomGenomes.html), 
but that's basically it! The only missing thing will be the cytobands, everything else should work just as fine!

If you have any problem reopen this issue and I'll try to help

Bernat
