### ISSUE TITLE
Bug in kpAddBaseNumbers

### ISSUE THREAD

**Issue by Baboon61** [bernatgel/karyoploteR#36]
Hello @bernatgel,
There is a bug in kpAddBaseNumbers, X-axis is 1-base offbeat from the plotKaryotype
`custom.genome <- GRanges(seqnames="chr12",ranges=IRanges(300000000,300000100),strand=NULL)
custom.coverage <- GRanges(seqnames=c("chr12","chr12","chr12"), ranges=c(IRanges(300000010,300000040),IRanges(300000050,300000055),IRanges(300000070,300000095)), strand=c("+","+","+"))
kp <- plotKaryotype(plot.type=1, genome = custom.genome)
kpPlotCoverage(kp, data=custom.coverage, show.0.cov=FALSE)
kpAddBaseNumbers(kp, tick.dist = 5, tick.col="red", minor.tick.dist = 1, minor.tick.col = "gray")`

`sessionInfo()`

> [1] karyoploteR_1.8.7

<a href="https://ibb.co/grkwC7w"><img src="https://i.ibb.co/WHmF13F/Capture-du-2019-03-26-11-01-45.png" alt="Capture-du-2019-03-26-11-01-45" border="0"></a>

If I may ask something else, I find the X-axis scale not informative enought when I try to zoom in, here on my example I want to zoom in from 300 000 000 to 300 000 100, would it be possible to display the full number of bases, not only 300(Mb) for each tick.

Something similar to set the digits option at 6, but without the dot and without the frame shifting

<a href="https://ibb.co/9b1k0qJ"><img src="https://i.ibb.co/5rSg35d/Capture-du-2019-03-26-11-22-08.png" alt="Capture-du-2019-03-26-11-22-08" border="0"></a>

Thanks a ton !

**Comment by bernatgel** [comment]
Hi @Baboon61 

Thanks a lot for the detailed report! 

I've slightly updated the code for kpAddBaseNumbers to fix this problem. At the same time, I've realized it's code could be improved quite a lot and I'll try to rewrite it for next release (by the end of April). In this new code I'll try to include your second suggestion.

In any case, this is corrected in version 1.8.8 (available in github and in Bioc in a couple of days) and in devel in version 1.9.15.
