### ISSUE TITLE
kpPlotGenes fails in data.panel=2 

### ISSUE THREAD

**Issue by bernatgel** [bernatgel/karyoploteR#39]
When plotting genes with kpPlotGenes in data.panel=2, the strand of the genes is flipped. Problems with the computation of the strand marks.

**Comment by dstern** [comment]
I get the same (incorrect behavior when use plot.type =2 and plot.type = 3 and data.panel = 2. Appears OK with plot.type = 1 or 4

**Comment by bernatgel** [comment]
Fixed in 1.13.7
