### ISSUE TITLE
plot specific chromosomes in custom genome

### ISSUE THREAD

**Issue by nbedelman** [bernatgel/karyoploteR#4]
Hi, I really like this package for plotting data along a genome, and it has worked well for me when I visualize the entire genome using a custom genome. However, when I try to only visualize a single chromosome, I get the error:
 "No valid genome specified and no cytobands provided. No cytobands will be passed to the ideogram plotter."
and the entire genome is plotted. My genome dataframe looks like this:

> Hmel2pt5Genome
   chromosome start      end chr
3        chr1     1 17206585   1
14       chr2     1  9045316   2
15       chr3     1 10541528   3
16       chr4     1  9662098   4
17       chr5     1  9908586   5
18       chr6     1 14054175   6
19       chr7     1 14308859   7
20       chr8     1  9320449   8
21       chr9     1  8708747   9
1       chr10     1 17965481  10
2       chr11     1 11759272  11
4       chr12     1 16327298  12
5       chr13     1 18127314  13
6       chr14     1  9174305  14
7       chr15     1 10235750  15
8       chr16     1 10083215  16
9       chr17     1 14773299  17
10      chr18     1 16803890  18
11      chr19     1 16399344  19
12      chr20     1 14871695  20
13      chr21     1 13359691  21

I converted to Grange object with this command:
Hmel2pt5GenomeGrange <- makeGRangesFromDataFrame(Hmel2pt5Genome, seqnames.field = "chromosome")

And the resulting Grange object looks like this:

> Hmel2pt5GenomeGrange
GRanges object with 21 ranges and 0 metadata columns:
     seqnames        ranges strand
        <Rle>     <IRanges>  <Rle>
   3     chr1 [1, 17206585]      *
  14     chr2 [1,  9045316]      *
  15     chr3 [1, 10541528]      *
  16     chr4 [1,  9662098]      *
  17     chr5 [1,  9908586]      *
  ..      ...           ...    ...
   9    chr17 [1, 14773299]      *
  10    chr18 [1, 16803890]      *
  11    chr19 [1, 16399344]      *
  12    chr20 [1, 14871695]      *
  13    chr21 [1, 13359691]      *
  -------
  seqinfo: 21 sequences from an unspecified genome; no seqlengths

Is there a different method I should use to create the genome? Or perhaps a specific field identifier I need to use? Thank you!

Nate

**Comment by bernatgel** [comment]
Hi @nbedelman, 

This is a bug in karyoploteR's code. I'll fix it and get back to you.

Thanks for reporting it.

Bernat

**Comment by bernatgel** [comment]
Ok, it's fixed now. It's fixed in both the devel version and the release version. It should be available on biocLite in a day or so, but you can install the fixed version from github if you need it faster.

Again, thanks for reporting it.

Bernat

**Comment by nbedelman** [comment]
Hi Bernat,
Thanks, it works great! I really appreciate you fixing it so fast.
Best,
Nate
