### ISSUE TITLE
Error when retrieving data computed by kpPlotDensity

### ISSUE THREAD

**Issue by c11cc** [bernatgel/karyoploteR#41]
Dear,
There is error when I use the karyoploteR for custom genome as follows.
> gme <- toGRanges("D:/work/experiment/transposon/lxq/script/function_combine/chr_info.txt")
> unit<- toGRanges("D:/work/experiment/transposon/lxq/script/function_combine/genome_info.txt")
> gme
GRanges object with 7 ranges and 0 metadata columns:
      seqnames    ranges strand
         \<Rle> \<IRanges>  \<Rle>
  [1] CP017553 1-2257857      *
  [2] CP017554 1-3044971      *
  [3] CP017555 1-3366276      *
  [4] CP017556 1-3629463      *
  [5] CP017557 1-4198534      *
  [6] CP017558 1-4002965      *
  [7] CP017559   1-47926      *
  \-------
> seqinfo: 7 sequences from an unspecified genome; no seqlengths
 unit
>GRanges object with 8772 ranges and 2 metadata columns:
         seqnames      ranges strand |      name            id
           \<Rle\>   \<IRanges\>  \<Rle\> | \<integer\>      \<factor\>
     [1] CP017553   1230-1648      * |         1 YALI1_A00014g
     [2] CP017553   1806-2173      * |         2 YALI1_A00019g
     [3] CP017553   3285-3920      * |         3 YALI1_A00032g
     [4] CP017553   5868-8531      * |         4 YALI1_A00058g
     [5] CP017553 10299-12134      * |         5 YALI1_A00102g
     ...      ...         ...    ... .       ...           ...
  [8768] CP017559 41321-41863      * |        52 YALI1_M00390g
  [8769] CP017559 42454-43596      * |        53 YALI1_M00390g
  [8770] CP017559 43776-45089      * |        54 YALI1_M00390g
  [8771] CP017559 45843-47252      * |        55 YALI1_M00458g
  [8772] CP017559 47272-47658      * |        56 YALI1_M00472r
  \-------
  seqinfo: 7 sequences from an unspecified genome; no seqlengths
> fig1<-plotKaryotype(gme,chromosome="CP017553",plot.type=2)
> kpPlotDensity(fig1,data=unit,r0=0,r1=0.3,window.size=10000)
> kpAxis(fig1, ymax=fig1$latest.plot$computed.values$max.density, r0=0, r1=0.3, cex=0.8)
> kpAbline(fig1, h=mean(fig1$latest.plot$computed.values$density), lty=2, ymax=fig1$latest.plot$computed.values$max.density, r0=0, r1=0.3)
Warning message:
In mean.default(fig1$latest.plot$computed.values$density) :
  argument is not numeric or logical: returning NA

I have tried :
> kpAbline(fig1, h=mean(data.matrix(fig1$latest.plot$computed.values$density)), lty=2, ymax=fig1$latest.plot$computed.values$max.density, r0=0, r1=0.27)
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

and 

> fig1$latest.plot$computed.values$density
NULL

The figures now showed as:
![image](https://user-images.githubusercontent.com/24308368/56494212-1f4ed980-6524-11e9-8150-1bc62044f6b8.png)

Any help is much appreciated.
Thanks.

**Comment by bernatgel** [comment]
Hi @c11cc 

The problem you have in your code is that you do not assign the result of `kpPlotDensity` back to `fig1`.

karyoploteR functions do not modify the parameter they receive, but return a modified version of the karyoplot. If you do not assign it back to your karyoplot object the changes are lost.

So you simply need to change your current line

    kpPlotDensity(fig1,data=unit,r0=0,r1=0.3,window.size=10000)

to this

    fig1 <- kpPlotDensity(fig1,data=unit,r0=0,r1=0.3,window.size=10000)

and it should work.

Hope this helps!

Bernat

PS: I think I'll add a page to the karyoploteR tutorial explaining this, since this is not thoroughly documented anywhere else.

**Comment by c11cc** [comment]
@bernatgel . It worked.  Thank you very much.
