### ISSUE TITLE
Add other genomes

### ISSUE THREAD

**Issue by cshen226** [bernatgel/karyoploteR#42]
Could you add other plant genomes ?

**Comment by bernatgel** [comment]
Hi @cshen226 

karyoploteR is not limited to any genome. If you have a plant genome you want to plot, you only need a GRanges (or a tabular file, or a data.frame) with the chromosome names and lengths. That's it. 

You can take a look at the [Custom Genomes](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/CustomGenomes/CustomGenomes.html) section of the [karyoploteR tutorial](https://bernatgel.github.io/karyoploter_tutorial/) to get more info on how to do that.

Hope this helps

Bernat

**Comment by cshen226** [comment]
Thank you very much！ I will learn it.
