### ISSUE TITLE
plotting lines is off by 1 chr

### ISSUE THREAD

**Issue by player5858** [bernatgel/karyoploteR#48]
Hello Bernat,

Awesome, package! I've got a (hopefully quick) question about plotting line data.

When I go to plot 'arbitrary data' over the karyotype (or chromosome), the data appears to be off by 1 chr (specifically, data for a particular chr is plotted on the chr directly preceding it).

You can see in the plot below just from the lengths of the line plotted, that it should go with chr4 and not chr3 (and the chr3 line data presumably is being plotted off the display here for chr2):
![issue1_plot](https://user-images.githubusercontent.com/47948203/62873967-5b35c680-bcee-11e9-96c0-32197e09a709.png)

Code to generate the plot:
```
library(karyoploteR)
input <- 'Sviridis_500_v2.0_NC028075.1_data.tsv'
df <- read.table(input,sep='\t',header=F)
custom.genome <- toGRanges(df)
c=c("Chr_03","Chr_04")
kp <- plotKaryotype(genome=custom.genome, chromosomes=c)

# input overlay data
input <- 'Sviridis_500_v2.0_NC028075.1_entropy100K.tsv'
entropy <- read.table(input,sep='\t',header=F)
custom.data <- toGRanges(entropy)
kpLines(kp, chr=seqnames(custom.data), x=end(ranges(custom.data)), y=custom.data$V5, data.panel = 1)
# add axis scale
kpAxis(kp, data.panel=1)
```

input 1:
```
head Sviridis_500_v2.0_NC028075.1_data.tsv 
Chr_01	1	41732233
Chr_02	1	47849963
Chr_03	1	50382502
Chr_04	1	39677845
Chr_05	1	46702114
Chr_06	1	36371416
Chr_07	1	35460007
Chr_08	1	40988899
Chr_09	1	56381885
NC_028075.1	1	138102
```

input 2:
```
head Sviridis_500_v2.0_NC028075.1_entropy100K.tsv 
Chr_01	1	100000	50001	1.99854
Chr_01	100001	200000	150001	1.99015
Chr_01	200001	300000	250001	1.99809
Chr_01	300001	400000	350001	1.99701
Chr_01	400001	500000	450001	1.99505
Chr_01	500001	600000	550001	1.99683
Chr_01	600001	700000	650001	1.98968
Chr_01	700001	800000	750001	1.99389
Chr_01	800001	900000	850001	1.98916
Chr_01	900001	1000000	950001	1.99147
```

Might be something simple in my code, not sure. This same issue occurs whether or not the entropy data is a data.frame. or a GRanges object (as shown above).

Appreciate any feedback, thanks!

**Comment by player5858** [comment]
Apparently I wasn't normalizing... I thought it performed this automatically.
Apologize, closing now!

**Comment by bernatgel** [comment]
Oook!! Glad it worked! :)
