### ISSUE TITLE
Rainfall plot - variants needed on all chromosomes?

### ISSUE THREAD

**Issue by sigven** [bernatgel/karyoploteR#49]
I am trying out the `kpPlotRainfall` function with some internal datasets (cancer genomes). I seem to get an error when variants are absent from a particular chromosome. Considering the demo dataset used in the [tutorial](https://bernatgel.github.io/karyoploter_tutorial//Examples/Rainfall/Rainfall.html), the error can be exemplified as follows when removing variants from chromosome 1:

`> sm <- sm %>% dplyr::filter(chr != "1")`
`> sm.gr <- toGRanges(sm[,c("chr", "start", "end", "ref", "alt")])`
`> seqlevelsStyle(sm.gr) <- "UCSC"`
`> kp <- plotKaryotype(plot.type = 4)`
`> kpPlotRainfall(kp, data = sm.gr)`

Error_ in attr(x, "tsp") <- c(1, NROW(x), 1) :  
 __attempt to set an attribute on NULL__

**Comment by bernatgel** [comment]
Fixed in 1.11.14
