### ISSUE TITLE
genome state HMM results for mm10

### ISSUE THREAD

**Issue by TheSallyGardens** [bernatgel/karyoploteR#57]
Hi Bernat!
A very good tool！
I want to create bigwig files for mouse，but I don't know the link for mm10’s genome state file.

**Comment by bernatgel** [comment]
Hi @TheSallyGardens 

I don't know if I'm getting your question correctly. 

If you want to create bigwig files from BAM files, you should be able to do it using deepTools (o other specific tools). karyoploteR can plot BigWig files, but cannot create them. This operation can be done for any genome (human, mouse, etc...) and karyoploteR can plot all of them

If you want to create an image similar to the [ENCODE Epigenetics example plot](https://bernatgel.github.io/karyoploter_tutorial//Examples/EncodeEpigenetics/EncodeEpigenetics.html) in the Tutorial page and want to add the chromHMM partitioning of the genome (which is optional), you'll have to locate a valid chromHMM file or build your own with your ChIP-seq experiments. As an example, at [this github repository](https://github.com/guifengwei/ChromHMM_mESC_mm10) they have built a chromHMM for mouse ES cells from mm10 mapped ENCODE BAM files, so maybe you could use this as a starting point.

Is this what you were asking?

Bernat

**Comment by TheSallyGardens** [comment]
Thank you for your help!

**Comment by TheSallyGardens** [comment]
> chromHMM file



> 
> 
> Hi @TheSallyGardens
> 
> I don't know if I'm getting your question correctly.
> 
> If you want to create bigwig files from BAM files, you should be able to do it using deepTools (o other specific tools). karyoploteR can plot BigWig files, but cannot create them. This operation can be done for any genome (human, mouse, etc...) and karyoploteR can plot all of them
> 
> If you want to create an image similar to the [ENCODE Epigenetics example plot](https://bernatgel.github.io/karyoploter_tutorial//Examples/EncodeEpigenetics/EncodeEpigenetics.html) in the Tutorial page and want to add the chromHMM partitioning of the genome (which is optional), you'll have to locate a valid chromHMM file or build your own with your ChIP-seq experiments. As an example, at [this github repository](https://github.com/guifengwei/ChromHMM_mESC_mm10) they have built a chromHMM for mouse ES cells from mm10 mapped ENCODE BAM files, so maybe you could use this as a starting point.
> 
> Is this what you were asking?
> 
> Bernat

 Excuse me .  Do you know if ENCODE has created a mouse's chromHMM file ？Just like  wgEncodeBroadHmmGm12878HMM.bed.gz  in your Tutorial page .

**Comment by bernatgel** [comment]
I'm sorry but no, I don't know if they produced any "official" chromHMM file for mouse.

**Comment by TheSallyGardens** [comment]
Thanks,bernatgel.
Good night！
