### ISSUE TITLE
How to save plot into a png file?

### ISSUE THREAD

**Issue by lakhujanivijay** [bernatgel/karyoploteR#58]
Hi

How to save plot into a png file? I have tried this but its not working

### Plotting the ideogram
`kp <- plotKaryotype(genome = "hg19", main="Copy Number data",plot.type=2, plot.params = pp)`

### Adding the cytoband information
`kpAddCytobandLabels(kp)`

### Save to png
```
png("plot.png",width = 15, height = 7)
dev.off()
```

**Comment by bernatgel** [comment]
Hi @lakhujanivijay 

You have all the ingredients, just in the wrong order. karyoploteR uses "R base graphics" wich work different than ggplot and the like with respect to saving to files. 

With base you need to:

1 - Open a device
2 - Draw
3 - Close de device

And one last important thing: each graphical device has its own units, pdf work with inches but png works with pixels, so the png call you've written would produce a tiiiiny png file of 15 per 7 pixels. I usually work with png file between 1000 and 3000 pixels in their longest side.

Therefore, with karyoploteR it would be

```
#Open the device
png("plot.png", width = 1500, height = 700)

#Draw
kp <- plotKaryotype(genome = "hg19", main="Copy Number data",plot.type=2, plot.params = pp)
kpAddCytobandLabels(kp)

#Close the device
dev.off()
```

And that would be it. If you find any other problem feel free to ask!

Bernat

PS: If you are working with Copy-Number data you can take a look at [CopyNumberPlots](https://bioconductor.org/packages/CopyNumberPlots/) a karyoploteR companion package we have developed with functions to plot copy-number related data, specially related to SNP-arrays.

**Comment by lakhujanivijay** [comment]
That was indeed helpful @bernatgel. And I will definitely look at CopyNumberPlots :+1:
