### ISSUE TITLE
Plotting a genome for GeneDensity 

### ISSUE THREAD

**Issue by Caro-Ca** [bernatgel/karyoploteR#68]
Hi!
I'm totally new in R and this is my first time using Karyoplote. 
I want to plot the genome of Saccharomyces cerevisiae. For that I did:
1.  a custom genome
2. and tried to download the one that is in: [https://bioconductor.org/packages/3.10/data/annotation/html/BSgenome.Scerevisiae.UCSC.sacCer1.html](url)
I want to plot the gene density and show the insertion and deletions that happen in each chromosome. 
For the gene density, I tried to follow this tutorial: [https://bernatgel.github.io/karyoploter_tutorial//Examples/GeneDensity/GeneDensity.html](url)
In one section says: 
```
 library(TxDb.Hsapiens.UCSC.hg19.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
all.genes <- genes(txdb)
head(all.genes)
```
In my case, how would it be? as the ones that I tried I get the message: 
`Error in genes(txdb) : could not find function "genes"`

Thank you in advance for your help

**Comment by bernatgel** [comment]
Hi @Caro-Ca 

Welcome to R and to karyoploteR :)

Your general approach to the problem is correct and you are almost there. The problem with genes is that most probably R gave you an error when loading the TxDb package.

I'd first suggest using [SacCer3[(https://bioconductor.org/packages/BSgenome.Scerevisiae.UCSC.sacCer3/) version of the genome, SacCer1 is from 2003! And then as TxDb you should use [TxDb.Scerevisiae.UCSC.sacCer3.sgdGene](https://bioconductor.org/packages/TxDb.Scerevisiae.UCSC.sacCer3.sgdGene/).

Make sure they are installed in your system
```
BiocManager::install("BSgenome.Scerevisiae.UCSC.sacCer3")
BiocManager::install("TxDb.Scerevisiae.UCSC.sacCer3.sgdGene")
```
Then, load them with library and you can use them to plot. The complete code would be something like:
```
library(karyoploteR)
library(BSgenome.Scerevisiae.UCSC.sacCer3)
library(TxDb.Scerevisiae.UCSC.sacCer3.sgdGene)

kp <- plotKaryotype(genome = BSgenome.Scerevisiae.UCSC.sacCer3)
all.genes <- genes(TxDb.Scerevisiae.UCSC.sacCer3.sgdGene)
kpPlotDensity(kp, data=all.genes, window.size = 10000)
```

Ah, and please note that we need to set `window.sise=10000` (or any other small value you prefer) in [kpPlotDensity](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/PlotDensity/PlotDensity.html) since the default value, 1 megabase, is too large for this genome size.

Hope this helps!

**Comment by Caro-Ca** [comment]
Thank you for your help. It was extremely helpful. On the other hand, I was looking at the packages for S. cerevisiae [https://bioconductor.org/packages/release/BiocViews.html#___Saccharomyces_cerevisiae](url) and if it is possible to plot the gene density, is there also a package for TE so I can plot the TE density? Or how can I load the TE annotation in a bed format that I already have? And again, thank you for your help.

**Comment by bernatgel** [comment]
Hi @Caro-Ca 

I'm not aware of any package with TE information, but if you have it in a BED file you can use a function called `toGRanges` to load it. This function is part of another package called `regioneR` but  it's available if you are using karyoploteR. It can load BED files or in general any other tabular file (csv, tab delimited... ) and convert it into a GRanges, the structure needed by `kpPlotDensity`.

With 
```
tes <- toGRanges("TE_file.bed")
```
you'll load the TE data, and then you can plot them directly with
```
kp <- plotKaryotype(genome = BSgenome.Scerevisiae.UCSC.sacCer3)
kpPlotDensity(kp, data=tes, window.size = 10000)
```

If you want to plot both values together, you can use [r0 and r1](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/DataPositioning/DataPositioning.html) to plot both  on top of the ideogram (take a look at [autotrack](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/Autotrack/Autotrack.html) if you want some help setting r0 and r1)
```
kp <- plotKaryotype(genome = BSgenome.Scerevisiae.UCSC.sacCer3)
kpPlotDensity(kp, data=all.genes, window.size = 10000, r0=0, r1=0.5)
kpPlotDensity(kp, data=tes, window.size = 10000, r0=0.5, r1=1)
```

Another option would be to plot one above and one below by selecting two [data.panels](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/DataPanels/DataPanels.html)

```
kp <- plotKaryotype(genome = BSgenome.Scerevisiae.UCSC.sacCer3, plot.type=2)
kpPlotDensity(kp, data=all.genes, window.size = 10000, data.panel=1)
kpPlotDensity(kp, data=tes, window.size = 10000,  data.panel=2)
```

Hope this helps :)

PS: Ah, in the future I'd suggest asking new questions you might have about karyoploteR in [biostars](https://www.biostars.org/) so others can benefit from them :) If you tag "karyoploteR" I should be notified, or you can send me an email to tell me there's a question I should answer!

**Comment by Caro-Ca** [comment]
That is a good idea. I'll do it on Biostars in the future. Your explanations were incredibly helpful that for sure somebody else can get this benefit, and don't get me wrong, as I really read the manual, but some parameters were difficult for me to understand the flow of the codes. Thank you, again!

**Comment by bernatgel** [comment]
Heheh!! don't worry! I know the manual is far from perfect and that there are quite a few concepts that are muuuuch more clear when someone shows how to apply them to your specific problem :) 

Oh, and if there are followup questions related to this we can keep using this issue!
