### ISSUE TITLE
Add different colors to the gene density

### ISSUE THREAD

**Issue by Sisov** [bernatgel/karyoploteR#7]
Dear author ,can the software add some color bars to the gene density. So that  we can plot different colors to display the gene density coverage?
Alex
![image](https://user-images.githubusercontent.com/22792569/35862160-8b0c7b0e-0b85-11e8-9c0f-ea31555c2d86.png)

**Comment by bernatgel** [comment]
Hi Alex,

The black bars in the plot are cytobands and their color is defined by their specific staining levels. If you want to plot gene density you 'll have to create a GRanges with the positions of genes and then use kpPlotDensity to compute the density and plot it.

You  can find an example on how to plot the density of human genes at the karyoploteR tutorial page at https://bernatgel.github.io/karyoploter_tutorial//Examples/GeneDensity/GeneDensity.html
