### ISSUE TITLE
error on karyoploteR

### ISSUE THREAD

**Issue by rthapa1** [bernatgel/karyoploteR#75]
Hi,

I am getting following error. Could you please suggest what went wrong?

Thanks

Error in plotKaryotype(zoom = "Chr01:3647-12170735", main = "BedGraphs",  : 
  You are trying to set the zoom to a region not part of the current genome.
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)

**Comment by lbeltrame** [comment]
A stupid suggestion: why not writing "chr1" instead of "Chr01"?

**Comment by bernatgel** [comment]
Yes, the error seems to be the name of the chromosomes. Chromosome names are their identifiers. They are case sensitive and so have to be written exactly as in the genome. Changing "Chr1:XXXX" to "chr1:XXXX" should solve this problem
