### ISSUE TITLE
Error plotKaryotype custom BSgenome

### ISSUE THREAD

**Issue by Aworwui** [bernatgel/karyoploteR#76]
Please help to resolve this error message from plotKaryotype BSgenome 
WARNING: There was an error when filtering the chromosomes and selecting only canonical chromosomes.  Falling back to using the unfiltered genome. 
Error in filterChromosomes(gr.genome, organism = genome.name, chr.type = chromosomes): In filterChromosomes: Organism  NC_v  ( NC_045512v2 ) not recognized. Available organisms are:  hg, mm, bosTau, ce, danRer, rheMac, rn, sacCer, dm, panTro

[1] "NC_045512v2"
Loading ideogram...
Error in `genome<-`(`*tmp*`, value = range) : 
  Failed to set session genome to 'NC_045512v2'
cytoBand informatin is not available, only get ranges.
Loading ranges...
Message: Failed to retrieve cytobands for NC_045512v2 from UCSC. Returning no cytobands.Error in GRangesForGenome(genome, chrom = chrom, ranges = ranges, method = "UCSC", : Failed to obtain information for genome 'NC_045512v2'

**Comment by bernatgel** [comment]
Hi  @Aworwui 

could you give me the call that generated this error? What did you write? So I can see what's going on.

Bernat
