### ISSUE TITLE
customize size of chromosome labels on x-axis?

### ISSUE THREAD

**Issue by conte1** [bernatgel/karyoploteR#77]
Hi,

I have been searching through the documentation and have not found a way to customize the size of the text on the x-axis ("Chr1", "Chr2", etc). Is there an option to do this?

Thanks,
Matt

**Comment by bernatgel** [comment]
Hi  @conte1 

Sure, you can simply specify a "cex" parameter in `plotKaryotype` to change the size of the chromosome names

`kp <- plotKaryotype(cex=4)`

If you want more control you can disable automatic plotting and adding them explicitly

`
kp <- plotKaryotype(labels.plotter = NULL)
kpAddChromosomeNames(kp, cex=4, srt=45, col="red")
`

I'll add making this more clear in the documentation to my TODO list! 

Hope this helps!

Bernat

**Comment by dstern** [comment]
It looks like the code is backwards for this function. It adds yoffset to x value and vice-versa.
Also, the behavior seems a little odd. Change "real" x by 0.1 moves text a lot, but changing "real" y by 10 moves a tiny bit.

function (karyoplot, xoffset = 0, yoffset = 0, ...) 
{
    karyoplot$beginKpPlot()
    on.exit(karyoplot$endKpPlot())
    bb <- getChromosomeNamesBoundingBox(karyoplot)
    chr.labels <- karyoplot$chromosomes
    x <- (bb$x0 + bb$x1)/2 + yoffset
    y <- (bb$y0 + bb$y1)/2 + xoffset
    graphics::text(x = x, y = y, labels = chr.labels, ...)
    invisible(karyoplot)
}
<bytecode: 0x7fb06f44a2b8>
<environment: namespace:karyoploteR>

**Comment by bernatgel** [comment]
Ouch! Thanks @dstern for spotting this!! I'll change it right away!

About the different x and y scales... yes, this is not obvious and not correctly explained anywhere. This difference stems from the very core of the package, the coordinate change functions going from genomic coordinates to plot coordinates, and would be quite difficult to address. 

I'll try to add a new section to the website with and explanation of this and why this happens. In summary, the x axis measures 1 unit, so all xoffsets are based on "the portion of the plot you want to move" (i.e. 0.1, move it 10% of the total plot) while y axis depends on the number of chromosomes, the margins and a whole lot of other parameters but usually ranges from hundreds to a few thousands. Hmm... maybe an option would be to have all offsets in the public API behaving as x currently does, and then scaling internally... I'll think about that.

Thanks again for reporting this!

**Comment by bernatgel** [comment]
Hi @dstern,

This has been fixed in devel (v1.15.1) and in the current release (v1.14.1). 

You can expect it to be available on BiocManager in a couple of days.

Thanks again for reporting this
