### ISSUE TITLE
KaryoploteR for copy number

### ISSUE THREAD

**Issue by rthapa1** [bernatgel/karyoploteR#78]
Hi,

I am trying to plot a genome-wide Copy number variation using KaryoploteR. I am getting an error saying duplicate chromosome names in the genome. But I have CN in several locations of the same chromosome. Does anyone have any idea? Thanks

> head(custom.genome)
GRanges object with 6 ranges and 1 metadata column:
      seqnames        ranges strand |      CN
         <Rle>     <IRanges>  <Rle> | <numeric>
  [1]    Chr01   38005-43167      * |  1.999678
  [2]    Chr01   43335-46922      * |  1.415342
  [3]    Chr01   50386-50877      * |  1.398499
  [4]    Chr01   76659-79583      * |   2.41541
  [5]    Chr01 102003-104811      * |  1.357889
  [6]    Chr01 105542-109696      * |  1.629476

> plotKaryotype(genome = custom.genome)
Error in plotKaryotype(genome = custom.genome) : 
  There are duplicate chromosome names in the genome. Chromosome names must be unique. Chromosome names are: Chr01, Chr01, Chr01, Chr01

**Comment by bernatgel** [comment]
Hi @rthapa1 

Why do you need a custom genome? Your genome should be your standard reference genome and the copy number status shoudl be the "data" you plot. You can use multiple plots for that, segments, heatmaps, etc.. each with its own function (kpSegments, kpHeatmaps...). Please refer to the vignette or the tutorial (https://bernatgel.github.io/karyoploter_tutorial/) for more information on these functions. 

In addition, if you are working with copy number data, I'd recommend you to give a try to CopyNumberPlots ( https://bioconductor.org/packages/CopyNumberPlots/ ), a new package we have developed, based on karyoploteR specifically for copy-number data, which can be pretty useful to you (it will even read you data into R).
