### ISSUE TITLE
Error messages during installation in R

### ISSUE THREAD

**Issue by Tman3** [bernatgel/karyoploteR#8]
During the execution of the following
`biocLite("karyoploteR")`
I received the following 2 error messages during the installation of *source* package 'rsconnect' ...

> appDependencies                         html  
Rd warning: K:/Temp/Windows Temp/RtmpCSsg3f/R.INSTALL216c2218440d/rsconnect/man/appDependencies.Rd:63: missing file link 'rsconnectPackages'

> proxies                                 html  
Rd warning: K:/Temp/Windows Temp/RtmpCSsg3f/R.INSTALL216c2218440d/rsconnect/man/proxies.Rd:9: missing file link 'rsconnectOptions'

I don't know how important they are.

I tried...
`library(karyoploteR)`
It returned the prompt.  Therefore, I just want to flag this and see whether anything I could do to "fix" the issues before going too far down the road.

**Comment by bernatgel** [comment]
Hi @Tman3 ,

karyoploteR does not directly use rsconnect and I'm not aware any of its dependencies does (but I might be wrong). 

In any case, have you tried updating to latest bioconductor? Could you try

    source("http://bioconductor.org/biocLite.R")
    biocLite()

and try again? If it doesn't work, could you send the output of sessionInfo()?

**Comment by Tman3** [comment]
Thank for the suggestion!
No more error messages

**Comment by bernatgel** [comment]
Great, glad it helped
