### ISSUE TITLE
Custom placement of chromosomes

### ISSUE THREAD

**Issue by mrvollger** [bernatgel/karyoploteR#80]
Hi, 

First wanted to say how much I love karyoploter, is has been of great use to me!

My question is, for a custom genome is there any way to do custom placements of chromosomes on the plot?
![image](https://user-images.githubusercontent.com/6935283/89126762-27265900-d49d-11ea-9641-a70e76b6075f.png)
For example I have the above plot, but it would be really great if I could place the chromosomes into two columns instead of one. 

Is there any way to do this?

Thanks! 
Mitchell

**Comment by bernatgel** [comment]
Hi Mitchell,

You can reorder the chromosomes but it is not possible to place them into
two different columns right now.

Sorry about that

Bernat

**Comment by mrvollger** [comment]
Too bad. But thanks for the quick response!
