### ISSUE TITLE
Issues with plotting using zoom fuction on server

### ISSUE THREAD

**Issue by Maillinia** [bernatgel/karyoploteR#95]
I am trying to zoom into a specific region of my chromosome. 
The code below works with no issue in R studio. 
![Plot Rstudio](https://user-images.githubusercontent.com/60882704/100367113-0a8cce80-3002-11eb-81df-354b454db2af.jpg)

However, when I run it in R on my server, it is not plotting the entire plot. Chr_22 is missing for some reason.
![Plot server](https://user-images.githubusercontent.com/60882704/100367141-1082af80-3002-11eb-8af0-fbf87e15c7d8.jpg)

### code
zoom.start <- 42121077
zoom.end <- 42131157
zoom.region <- toGRanges(data.frame(Chr_no, zoom.start,zoom.end))  

Chr_no <- "Chr_22"
genome_file <- 'genome.txt'
cytoband_file <- read.table('cyto.txt', header=TRUE)
custom.genome <- toGRanges(genome_file)
cyto.target <- cytoband_file[c(1,2,3),]
cyto.chr <- cytoband_file[(4),]
custom.cyto.target <- toGRanges(cyto.target)
custom.cyto.chr <- toGRanges(cyto.chr)

jpeg('karyoploteR.jpg', width=2400,height=1800, res=300)
kp <- plotKaryotype(genome = custom.genome, cytobands = custom.cyto.chr, chromosomes=Chr_no, zoom=zoom.region, plot.type = 5, labels.plotter=NULL)
par(new=TRUE)
kp <- plotKaryotype(genome = custom.genome, cytobands = custom.cyto.target, chromosomes=Chr_no, zoom=zoom.region, plot.type = 5, labels.plotter=NULL)
kpAddCytobandLabels(kp, force.all = TRUE, cex=0.75)

### files 
**genome.txt:**
Chr_01  1       248956423
Chr_02  1       242193530
Chr_03  1       198295560
Chr_04  1       190214556
Chr_05  1       181538260
Chr_06  1       170805980
Chr_07  1       159345974
Chr_08  1       145138637
Chr_09  1       138394718
Chr_10  1       133797423
Chr_11  1       135086623
Chr_12  1       133275310
Chr_13  1       114364329
Chr_14  1       107043719
Chr_15  1       101991190
Chr_16  1       90338346
Chr_17  1       83257442
Chr_18  1       80373286
Chr_19  1       58617617
Chr_20  1       64444168
Chr_21  1       46709984
Chr_22  1       50818469
Chr_X   1       156040896
Chr_Y   1       57227416
Chr_MT  1       16570

**cyto.txt:**
chr     start   end     name    gieStain
Chr_22  42126499        42130881        CYP2D6  stalk
Chr_22  42126490        42126623        qPCR    acen
Chr_22  42126077        42126157        PCR    acen
Chr_22  1       50818469        Chr_22  gvar

**Comment by bernatgel** [comment]
Hm... that strange... could you check the server and your machine are running the same version? You can use sessionInfo() to see if there are any differences... Other than that, I don't know what  might be going on.

**Comment by Maillinia** [comment]
I'm running R version 3.6.1 in Rstudio, and version 4.0.3 on the server. Perhaps that's the issue?
I have attached the session infos.

[Server.txt](https://github.com/bernatgel/karyoploteR/files/5607444/Server.txt)
[Rstudio.txt](https://github.com/bernatgel/karyoploteR/files/5607451/Rstudio.txt)

**Comment by bernatgel** [comment]
Ok, this explains the differences, but the one failing is the newer one, which is strange. I'll take a look at it.

Bernat

**Comment by bernatgel** [comment]
Ok, I see whats happening, I think.

This "par(new=TRUE)" part to create 2 karyoplots one on top of the other is a bit too hacky and might function differently in Rstudio and out of it (the server). 

I'd recommend explicitly plotting rectangles on top of the ideogram using data.panel="ideogram" and `kpRect` and `kpText` instead of piggybacking on the cytoband drawing functionality. This will give you much more control and freedom and make you code cleaner.

```
Chr_no <- "Chr_22"

zoom.start <- 42121077
zoom.end <- 42131157
zoom.region <- toGRanges(data.frame(Chr_no, zoom.start,zoom.end))
```
(You could just use hg38 as your genome and you would not need to load it, althought you'd need to change the chromosome names to the standard ones (no caps)).
```
genome_file <- 'genome.txt'
custom.genome <- toGRanges(genome_file)
```
Now load the regions you want to plot (cyto.txt) and get a color for each of them. I'm using the cytoband colors here just to get you the exact same image you had before.

```
regs <- toGRanges('cyto.txt')[1:3] #The fourth line is no longer needed
cyto.cols <- getCytobandColors()
regs$color <- cyto.cols[regs$gieStain]
```

And then we're ready to plot. We'll set cytobands=NULL so they all appear as a gray rectangle and then plot rectangles and text on top of them. Most important idea is to use `data.panel="ideogram"` to be able to plot on top of the ideograms.

```
#Create the karyoplot. Setting cytobands=NULL will plot the ideograms as gray boxes (the background you needed)
png("github_issue_95.png", width=1000, height=800)
  kp <- plotKaryotype(genome = custom.genome, cytobands = NULL, zoom=zoom.region, plot.type = 5, labels.plotter=NULL)
  kpRect(kp, data = regs, y0=0, y1=1, col=regs$color, data.panel="ideogram")
  kpText(kp, data=regs, y=0.5, labels = regs$name, data.panel="ideogram")
dev.off()
```
(Note I'm using png instead of jpg. This will work much better (no artifacts) for line drawings such the ones produced by karyoploteR)

![image](https://user-images.githubusercontent.com/919489/100462067-fa402680-30c9-11eb-821f-8774038added.png)

And since you are just drawing rectangles and text, you have more freedom, for example, to move the text out of the ideogram, change colors, etc...

```
png("github_issue_95_2.png", width=1000, height=800)
  kp <- plotKaryotype(genome = custom.genome, cytobands = NULL, zoom=zoom.region, plot.type = 5, labels.plotter=NULL)
  kpRect(kp, data = regs, y0=0, y1=1, col=c("dodgerblue", "gold", "gold"), data.panel="ideogram")
  kpText(kp, data=regs, y=1.1, pos=1, labels = regs$name, data.panel="ideogram", clipping=FALSE)
dev.off()
````
![image](https://user-images.githubusercontent.com/919489/100462562-bd286400-30ca-11eb-9057-6cac76ea8b58.png)

**Comment by Maillinia** [comment]
Thank you! I will try to implement your suggestions :)

**Comment by bernatgel** [comment]
Great. Let me know if you find more problems!

**Comment by Maillinia** [comment]
I am still having the same issue with the chromosome not being plottet when I do zoom on the server.
I also have to use different y-coordinates for the text for the server and in R studio.  

genome_file <- 'genome_file.txt' #same as before
cytoband_file <- read.table('cyto.txt', header=TRUE) #removed the fourth line (chr_22)
custom.genome <- toGRanges(genome_file)
cyto <- toGRanges(cytoband_file)

### Plot on server
png('Plot.Server.png', width=2400,height=1800, res=300)
kp <- plotKaryotype(genome = custom.genome, cytobands = NULL, zoom=zoom.region, plot.type = 5, labels.plotter=NULL)
kpRect(kp, data = cyto, y0=0, y1=1, col=c("#96bf21", "#ce1d31", "#ce1d31"), data.panel="ideogram")
kpText(kp, data = cyto, y=(-1), pos=1, labels=cyto$name, data.panel="ideogram", clipping=FALSE, cex=0.5)
dev.off()
![Plot Server](https://user-images.githubusercontent.com/60882704/100601270-ac623300-3302-11eb-96d7-04b188332810.png)

### Plot in R studio
png('Plot.Rstudio.png', width=w,height=h, res=r)
kp <- plotKaryotype(genome = custom.genome, cytobands = NULL, zoom=zoom.region, plot.type = 5, labels.plotter=NULL)
kpRect(kp, data = cyto, y0=0, y1=1, col=c("#96bf21", "#ce1d31", "#ce1d31"), data.panel="ideogram")
kpText(kp, data = cyto, y=2, pos=1, labels=cyto$name, data.panel="ideogram", clipping=FALSE, cex=0.5)
dev.off()
![Plot Rstudio](https://user-images.githubusercontent.com/60882704/100601286-aff5ba00-3302-11eb-9c5a-657bc9b988f5.png)


I've made a work around plotting the zoom region using kpRect:
![Plot Server zoom](https://user-images.githubusercontent.com/60882704/100607219-e8999180-330a-11eb-9fce-df586f841d1c.png)

**Comment by bernatgel** [comment]
Ok, that's weird. It should work both in Rstudio and out of it, and I frequenly use karyoploteR invoked via Rscript, so it should'nt be a problem with non-interactive sessions. And the most strange fact is that `y=-1` you need on the server, right now I don't know what might be going on.

In any case, glad you found a workaround and thank you for getting back to me with the additional problem. 

Bernat
