### ISSUE TITLE
remove cytobands

### ISSUE THREAD

**Issue by gbdias** [bernatgel/karyoploteR#96]
Hi @bernatgel ,

I am trying to remove the cytobands from my plot, but the following command still generates a plot with cytobands.
```r
kp <- plotKaryotype(genome = 'dm6', cytobands = NULL)
```

My current workaround this is to create a custom genome for dm6 from a bed file, but I was wondering is there is something wrong with my command above. I'm using version 1.10.2.

Thanks,
Gui

**Comment by bernatgel** [comment]
Hi @gbdias 

Yes, I've been recently missing some more flexibility on cytoband plotting, so I'll think I'll try to improve it for the next release. In the meantime, as a workaround simpler than the custom genome, you can create a plot with no cytobands (all chromosomes as grey boxes) passing an empty GRanges as the cytobands

```
kp <- plotKaryotype(cytobands = GRanges())
```

Is there anything else you'd like to do with cytoband plotting that is not currently supported (or documented)?

**Comment by gbdias** [comment]
- Thanks for the tip @bernatgel !
- A color parameter for de ideogram could be useful too. Currently I use kpPlotRegions to draw over the ideograms with a different color.

thanks

**Comment by gbdias** [comment]
As for cytobands I actually don't use them a lot.
thanks

**Comment by bernatgel** [comment]
Great, thanks for the suggestion

**Comment by scienception** [comment]
Was this ever solved? I am still unable to remove cytobands and `GRanges()`  is not what I was looking for (grey boxes for no reason). I'd appreciate it if you could implement this. 
Also, is it possible to rename chromosomes by number only instead of chr1, chr2, etc?

Thanks!
