### ISSUE TITLE
Trouble in color centromere

### ISSUE THREAD

**Issue by KhanhLPBao** [bernatgel/karyoploteR#99]
Hi, I just begin with R and I found your package. I'm having trouble in the centromere color of 3 default color scheme. I need the centromere to have different color than red because I use red for indicating something in my project and it may cause misread for people. I have tried but I don't know how to color the centromere with color.table, it always return colorless chromosome while the 3 default scheme always returned with red centromere. Can you help me?
Thank you very much

**Comment by bernatgel** [comment]
Hi @KhanhLPBao 

The easiest option is to retrieve the default colors with `getCytobandColors` which will return a valid color.table, then modify the centrometer color (the "acen" slot) and finally plot the karyoplot giving it the new color.table

```
library(karyoploteR)
col.table <- getCytobandColors()
col.table["acen"] <- "green"
kp <- plotKaryotype(color.table=col.table)
```

You'll get a warning about a graphical parameter, but i'ts sfe to ignore that. 

Hope this helps
